name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Analysis
      run: C/C++ CI enable=all 3_Implementation
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
